package com.example.Model.unit;

public enum UnitAbility {
	ROUGH_TERRAIN_PENALTY,
	NO_DEFENSIVE_BONUS,
	IGNORE_TERRAIN_COST,
	BONUS_VS_MOUNTED_100,
	BONUS_VS_CITY_10,
	LIMITED_VISIBILITY,
	CAN_MOVE_AFTER_ATTACK,
	BONUS_VS_TANK_10,
	INDIRECT_FIRE,
	PENALTY_VS_CITY_10;
}
